# Generated by Django 5.2.1 on 2025-06-18 21:58

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_trip_budget_limit_trip_description_trip_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['-created_date']},
        ),
        migrations.RemoveField(
            model_name='trip',
            name='location',
        ),
        migrations.AddField(
            model_name='destination',
            name='arrival_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='departure_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='nights_staying',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='order',
            field=models.IntegerField(default=1, help_text='Order of visit in this plan'),
        ),
        migrations.AddField(
            model_name='plan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plan',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='name',
            field=models.TextField(default=datetime.datetime(2025, 6, 18, 21, 58, 43, 826400, tzinfo=datetime.timezone.utc), help_text="e.g., 'Option A', 'Beach Route', 'Budget Plan'"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='project.plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='project.trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(),
        ),
    ]
