# Generated by Django 5.2.1 on 2025-06-20 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_plan_options_remove_trip_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('profile1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile1', to='project.profile')),
                ('profile2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile2', to='project.profile')),
            ],
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_name', models.TextField(help_text="e.g., 'Paris', 'Bali', 'Tokyo'")),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('target_year', models.IntegerField(blank=True, help_text='Year you hope to visit', null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='project.profile')),
            ],
            options={
                'ordering': ['-added_date'],
            },
        ),
    ]
