# Generated by Django 5.2.1 on 2025-06-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_tripmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripmember',
            name='role',
            field=models.CharField(choices=[('organizer', 'Organizer'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
