# Generated by Django 5.2.1 on 2025-06-26 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_triplistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='triplistitem',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='project.plan'),
        ),
    ]
